version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/workspace:cached
      - bundle-volume:/workspace/vendor/bundle
      - node-module-volume:/workspace/node_modules
    depends_on:
      - postgres
    command: bash -c 'rm -f ./tmp/pids/server.pid && bin/rails s -b 0.0.0.0'
  postgres:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: codebase
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    command: postgres -c log_destination=stderr -c log_statement=all
    logging:
      options:
        max-size: "10k"
        max-file: "5"

volumes:
  postgres-volume:
  bundle-volume:
  node-module-volume:
